### ISSUE TITLE
Do you need to activate something in Squid before fetching metrics?

### ISSUE THREAD

**Issue by raypettersen** [boynux/squid-exporter#1]
I'm testing the exporter, and not getting any output. Got the feeling I'm missing something in squid.conf, but I have no idea what and documentation for the exporter doesn't mention anything.

**Comment by boynux** [comment]
the default configuration for squid should work. You don't need to do anything special.
Can you try to fetch metrics directly from the exporter and see what happens?

curl https://localhost:9301/metrics

**Comment by boynux** [comment]
Can you try the new version (v0.2) I added an additional error message when we can't fetch the metrics. So if you try to fetch the metrics and exporter can't reach Squid you should see some error messages.

**Comment by boynux** [comment]
Please try v0.3. Closing this issue.
