### ISSUE TITLE
Add build instructions to README

### ISSUE THREAD

**Issue by iDemonix** [boynux/squid-exporter#10]
Would it be possible to have some sort of build instructions on creating the binary?

I need to use the exporter but I don't use Go. I installed Go on two different machines and attempted to compile, but just get loads of errors around vendoring and other noise, example:

```
[root@dev01 squid-exporter]$make
go test -v ./...
vendor/github.com/prometheus/common/expfmt/encode.go:23:2: use of internal package not allowed
make: *** [test] Error 1
```

**Comment by sachk** [comment]
There's a statically linked binary in the docker container. It can be built as such using a recent version of go.

```bash
go get github.com/boynux/squid-exporter
cd ~/go/src/github.com/boynux/squid-exporter
CGO_ENABLED=0 GOOS=linux go install -a -ldflags '-extldflags "-static"' .
```
You'll end up with a binary in ~/go/bin called squid-exporter that's fully statically compiled and has no dependencies, not even glibc.

**Comment by boynux** [comment]
Or simply:

`go install github.com/boynux/squid-exporter`

will give you:

`$GOPATH/bin/squid-exporter` dynamically linked binary for the current OS.

**Comment by boynux** [comment]
Added some more info in README
