### ISSUE TITLE
Add option to add  prefix to metrics names...

### ISSUE THREAD

**Issue by ArcticSnowman** [boynux/squid-exporter#25]
The current metrics names exported have fairly generic names and in a large prometheus setup this could cause clashes between differing systems.

It might be nice to have an option `--prefix=<string>` that would add a prefix to the beginning of the metrics.

**Comment by boynux** [comment]
Hi @ArcticSnowman 

thanks for suggestion this improvement. to keep things more standard, if you refer to Prometheus best practices for metric naming [here](https://prometheus.io/docs/practices/naming/) is not a best practice to use arbitrary namesapce (prefix) for metric names.

On the other hand I see the problem that you are facing, do you think adding labels to metrics can solve your issue? 

some thing like `squid-exporter --label site="site-a" --label rack="rack-b"`?

**Comment by boynux** [comment]
Hi @ArcticSnowman 

In v1.6 you can have additional labels for your metrics as described below:

`squid-exporter -label rack="rack-a" -label site="site-b"`

Let me know if you need further assistance.

**Comment by ArcticSnowman** [comment]
Hmm Label might well work..

**Comment by boynux** [comment]
@ArcticSnowman then I close this issue, please reopen if labels didn't solve your problem 👼
