### ISSUE TITLE
Add documentation about http_access allow manager

### ISSUE THREAD

**Issue by kylesloan** [boynux/squid-exporter#28]
First, thanks for this project!  Saved me much time.

I ran into an issue where squid_up was returning 1, but I got no other squid_* items in my exporting.

My issue was that squid was running in a container, as was the squid exporter.  Thus I needed to open up some more access in my squid.conf

```
#http_access allow manager localhost
acl prometheus src 172.20.0.0/16
http_access allow manager prometheus
```

I thought this might be helpful in the readme as a requirement or a troubleshooting FAQ.

**Comment by boynux** [comment]
@kylesloan thanks you for reporting that. I think `squid_up` should not return `1` in such cases.
I'll add the description in README with the correct squid config.

**Comment by boynux** [comment]
@kylesloan I fixed the issue, now the proper error will be printed out if the settings are not correct.
