### ISSUE TITLE
Add option to use non-proxy authorization

### ISSUE THREAD

**Issue by Stogas** [boynux/squid-exporter#29]
With this Squid version 3.5.27 configuration:
```
acl manager proto cache_object
http_access allow localhost manager
http_access deny manager
http_access allow localhost
cachemgr_passwd <password> all
```

When running squid-exporter from localhost, it is necessary to pass the cachemgr password using the `Authorization` header instead of `Proxy-Authorization` for a successful counter collection.

It would be great if we could optionally pass both `Authorization` credentials as well as `Proxy-Authorization`, with separate command-line arguments.

**Comment by boynux** [comment]
@Stogas I created a PR to add this option, can you have look and possibly test it please?
