### ISSUE TITLE
Bump Go version to 1.13

### ISSUE THREAD

**Issue by pharaujo** [boynux/squid-exporter#35]
I'm considering submitting a PR to bump the Go version used to compile squid-exporter to 1.13. Since go modules are already being used in the project and go 1.13 started using them instead of vendor'd dependencies by default, I would like your opinion about deleting the `vendor` directory. In my opinion, it shouldn't be needed anymore. wdyt?

**Comment by boynux** [comment]
That's a good idea to use 1.13, I also like the idea of using go mod (`go.mod`, `go.sum`) but I'd still keep the vendor. Because no internet access when building the package is required and there will be no hard dependency on upstream availability.
