### ISSUE TITLE
Outdated version in binary

### ISSUE THREAD

**Issue by pharaujo** [boynux/squid-exporter#38]
**Describe the bug**
The last 4 releases show the exact same version (1.8) in the `-version` flag and in the `squid_exporter_build_info` metric, as the [VERSION](https://github.com/boynux/squid-exporter/blob/dc0b62db6b301860a7a38373b6d98878f956d21c/VERSION) file hasn’t been updated before releases.

**To Reproduce**
`squid_exporter_build_info` metric has the `version` label set to 1.8 on newer releases; the `-version` flag shows the same.

**Expected behavior**
both metric and flag should show the actual release (e.g. ”1.8.3”)

**Additional context**
Outdated [VERSION](https://github.com/boynux/squid-exporter/blob/dc0b62db6b301860a7a38373b6d98878f956d21c/VERSION) file

**Comment by boynux** [comment]
Thank you for reporting this. I'll fix it
