### ISSUE TITLE
Could not fetch metrics from squid instance

### ISSUE THREAD

**Issue by amrmohamady** [boynux/squid-exporter#40]
Could not fetch metrics from squid instance:  dial tcp 127.0.0.1:3128: connect: connection refused

**Comment by boynux** [comment]
Hi @amrmohamady,

This sounds to me like a network issue. I need more details of your setup to be able to help. Could you see if you can telnet to the squid instance?:

`telnet 127.0.0.1 3128` 

If that doesn't work you need to check if the squid is running and listening to that port correctly.
