### ISSUE TITLE
Repetitive errors on Time Percentiles

### ISSUE THREAD

**Issue by lotusnoir** [boynux/squid-exporter#44]
Hello, i've just installed the version 1.9.1 and i get some errors:

`servicec times - could not parse line: Service Time Percentiles 5 min 60 min:`

I had no problem with the version 1.8.3.

OS: debian 10
Squid version: 4.6-1+deb10u4
squid exporter version: 1.9.1

**Comment by lotusnoir** [comment]
Hello, i've just read more carefully your update comment on 1.9.1 and i saw you added an option to simply deactivate the "extractservicetimes"

So i tried to set` -extractservicetimes false` on init file or export `SQUID_EXTRACTSERVICETIMES=false`
but the error is still on...

Thanks for your work btw :)

**Comment by boynux** [comment]
Hi @lotusnoir,

Let me check to see if the flag is working as intended. Your issue as you explained seems to be related to the new feature.

**Comment by boynux** [comment]
@lotusnoir are you using Docker or running exporter from binary? I tried the binary with the `-extractservicetimes=false` and with the env `SQUID_EXTRACTSERVICETIMES=false` and both seem to disable the service time extraction.

If you are using Docker please try passing the env via `-e SQUID_EXTRACTSERVICETIMES=false` to Docker run. Otherwise could you please share your `init` file with me to see what's the issue?

**Comment by szenti** [comment]
Hello @boynux. I've just added the environmental variable SQUID_EXTRACTSERVICETIMES (set to "false") to a squid-exporter conatiner in our kubernetes cluster and the error messages are gone.

**Comment by swq499809608** [comment]
Error Info: Could not fetch service times metrics from squid instance:  error getting service times: Non success code 400 while fetching metrics

run commands:  ./squid-exporter -squid-hostname `hostname`  -squid-port 80  -listen 0.0.0.0:9301 

squid running is workers 36
Configure: 

workers 36
#if ${process_number} = 1
#include /usr/local/squid/etc/acl/frontend.conf
#else
#cpu_affinity_map process_numbers=1,2,3,4 cores=5,6,7,8
include /usr/local/squid/etc/frontend.conf
#endif

**Comment by jspashett** [comment]
The initial error is due to the "header line" squid outputs, and should probably be ignored:

`servicec times - could not parse line: Service Time Percentiles 5 min 60 min:`

I don't really do go programming, but the patch I have for it looks like this:


```
diff --git a/collector/client.go b/collector/client.go
index 68e9d05..55a1286 100644
--- a/collector/client.go
+++ b/collector/client.go
@@ -128,7 +128,9 @@ func (c *CacheObjectClient) GetServiceTimes() (types.Counters, error) {
                if err != nil {
                        log.Println(err)
                } else {
-                       serviceTimes = append(serviceTimes, s)
+                       if s.Key != "" {
+                               serviceTimes = append(serviceTimes, s)
+                       }
                }
        }
 
@@ -178,6 +180,9 @@ func decodeCounterStrings(line string) (types.Counter, error) {
 }
 
 func decodeServiceTimeStrings(line string) (types.Counter, error) {
+       if strings.HasSuffix(line, ":\n") { // A header line isn't a metric
+               return types.Counter{}, nil
+       }
        if equal := strings.Index(line, ":"); equal >= 0 {
                if key := strings.TrimSpace(line[:equal]); len(key) > 0 {
                        value := ""


```

**Comment by boynux** [comment]
If you make that a PR, illzbe happy to review and merge.

Thanks
