### ISSUE TITLE
Is it possible to monitor multiple ports on the same host?

### ISSUE THREAD

**Issue by haozhou** [boynux/squid-exporter#47]
My Squid instance listens on multiple ports on the same host.
Is that possible to specify multiple ports in the exporters instead of running multiple instances of the exporter?

Thanks

**Comment by boynux** [comment]
Hi,

 At he moment squid exporter can only connect to one squid port. I'm not exactly sure why you want to fetch metrics from multiple ports from one squid instance? I think if you configure the squid mgr correctly it should be able to export the aggregated metrics, am I missing something?

**Comment by haozhou** [comment]
Sorry for the late reply. My original question is whether it's possible to use one squid-exporter to export metrics of multiple squid instances (running on different ports)

**Comment by boynux** [comment]
Ok, now I understood the question. Unfortunately this not supported at the
moment, you will need one exporter per squid instance.
