### ISSUE TITLE
squid_process_open_fds metrics not getting exposed.

### ISSUE THREAD

**Issue by siju-vasudevan** [boynux/squid-exporter#51]
**Describe the bug**
Provided the PID file but not exposing squid_process_open_fds metrics. The below metrics are getting exposed except squid_process_open_fds metrics.

squid_process_cpu_seconds_total
squid_process_max_fds
squid_process_resident_memory_bytes
squid_process_start_time_seconds
squid_process_virtual_memory_bytes
squid_process_virtual_memory_max_bytes

**To Reproduce**
You can enable the pid file option and test it.

**Expected behavior**
Expose  squid_process_open_fds metrics

**OS (please complete the following information):**
 - OS: SUSE SLES12 SP4
 - Squid Version : 1.9.4 

**Additional context**

**Comment by boynux** [comment]
I checked and I can confirm open_fds metric is missing, but I'm not sure why. It seems something to do with prometheus client itself.

**Comment by boynux** [comment]
I think there is a permission issue

`error collecting metric Desc{fqName: "squid_process_open_fds", help: "Number of open file descriptors.", constLabels: {}, variableLabels: []}: open /proc/23278/fd: permission denied`

can you try to run the exporter as the same user as squid or as root and see if that fixes the issue?

I tested it as root and it seems everything is working as expected: 

```
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 10
```

**Comment by boynux** [comment]
You can also set `CAP_DAC_READ_SEARCH` capability for squid exporter process if you don't want to run it as root, which is probably a better option.

eg.

`sudo setcap 'cap_dac_read_search+ep' ./bin/squid-exporter`
