### ISSUE TITLE
Get metrics from differents Squid Proxy servers

### ISSUE THREAD

**Issue by IVBB** [boynux/squid-exporter#53]
Hi!!!

This is more a question than a bug report. Is there any way to get metrics from different Squid Proxy servers with the same exporter instance? Or is mandatory to run an exporter for each Proxy Server??

Thank you in advance!!!

**Comment by boynux** [comment]
Hi,

No, at the moment there is no way to connect one exporter to multiple servers. So it's one exporter per squid instance.
