### ISSUE TITLE
recommended grafana dashboard?

### ISSUE THREAD

**Issue by juju4** [boynux/squid-exporter#55]
Thanks for your work!

testing squid exporter along prometheus and grafana, but most community grafana dashboards for squid don't seem fully functional.
https://grafana.com/grafana/dashboards/?search=squid

any recommendations?

**Comment by boynux** [comment]
Hi @juju4 

Unfortuantely I don't have any sample dashboards, but I'll appreciate of you created or find anything suitable include that to the project.

Thank you

**Comment by boynux** [comment]
There is a dashboard file included in the project already in PR #12
