### ISSUE TITLE
Docker Hub tags problem   

### ISSUE THREAD

**Issue by AnaTorres** [boynux/squid-exporter#56]
I wanted to highligth an issue on dockerhub about the tags.

In docker hub, there is no v1.10.0 tag eventhought there is a code version in github  with this tag. 
The digest of the tag "latest"   does not correspond to the latest tag (v1.9.4) available on dockerhub. I assume the tag latest is actually the v1.10.0. 
It would be useful to be able to use the version V1.10.0 without using the tag latest

**Comment by boynux** [comment]
It seems Docker hub has disabled it's automated builds for its personal tier and it really sucks!

I'll see if I can find another way to publish the images.

**Comment by boynux** [comment]
I moved the build to Travis, from now all the tagged commit should build normal with a reference to the latest tag: docker pull boynux/squid-exporter:v1.10.3

**Comment by boynux** [comment]
Thank you for reporting this issue.
