### ISSUE TITLE
could not parse line

### ISSUE THREAD

**Issue by VR6Pete** [boynux/squid-exporter#6]
Have setup exporter, and getting alot of console messages every time I hit the metrics end point http://xxxxx:9301/metrics

2018/07/06 11:04:45 could not parse line
2018/07/06 11:04:45 could not parse line
2018/07/06 11:04:45 could not parse line
2018/07/06 11:04:45 could not parse line
2018/07/06 11:04:45 could not parse line
2018/07/06 11:04:46 could not parse line
2018/07/06 11:04:47 could not parse line
2018/07/06 11:04:48 could not parse line
2018/07/06 11:04:48 could not parse line
2018/07/06 11:04:48 could not parse line
2018/07/06 11:04:49 could not parse line
2018/07/06 11:04:49 could not parse line
2018/07/06 11:04:49 could not parse line
2018/07/06 11:04:50 could not parse line

Any idea what could be causing this to occur or additional debug I enable to assist?

**Comment by boynux** [comment]
I think parser can not read the squid manager output, can you check your squid metrics output and see if that works properly? 

you can try `squidclient mgr:info` to see the output.

**Comment by boynux** [comment]
@Gmax76 what's the squid version?

**Comment by Gmax76** [comment]
@boynux This commit works for me, no more error message and everything seems to be fine.

**Comment by boynux** [comment]
OK, I'll release a new version thanks for testing it.
