### ISSUE TITLE
docker image for arm64 platform 

### ISSUE THREAD

**Issue by prajith-nair** [boynux/squid-exporter#69]
Hi, 

I am running `Linux staging_proxy  4.14.309-231.529.amzn2.aarch64 #1 SMP Tue Mar 14 23:45:16 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`

Please let me know if docker image for squid-proxy aarch64 will be published to docker hub.

`docker run -p 9301:9301 -d boynux/squid-exporter -squid-hostname "staging_proxy" -squid-port 3128 -listen ":9301"`

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by prajith-nair** [comment]
@boynux  - Thanks for letting me know. I will proceed to use Docker file from the repo to build an image that supports arm64 and reach out to you, should I hit any road blocks.

**Comment by boynux** [comment]
I change the build system from Travis (which didn't work due to credit issues) to Github Actions. Now I'm able to push docker images again, but unfortunately, Github actions doesn't provide arm build environment for Docker buildx capability.

**Comment by anonfriese** [comment]
Would be great to also have the arm64 Binaries published as GitHub release as well I think, similar to how other Go-based Binaries are typically published.
