### ISSUE TITLE
Binary missing in last release v1.10.4

### ISSUE THREAD

**Issue by DanielViard** [boynux/squid-exporter#74]
Hello,

I'm facing an unexpected 404 error when trying to download the latest release the same way I was doing before (I'm using script to automate my deployments).

Thank you, regards.

**Describe the bug**
The binary is missing in the lastest release v1.10.4

**To Reproduce**
Try to download the release using the URL https://github.com/boynux/squid-exporter/releases/download/v1.10.4/squid-exporter
get an 404 error instead of the squid-exporter binary.

**Expected behavior**
Download the squid-exporter binary like the other versions (for instance https://github.com/boynux/squid-exporter/releases/download/v1.9.4/squid-exporter).

**OS (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version v1.10.4

**Additional context**
Not really a bug but an incomplete release.

**Comment by boynux** [comment]
Thank you for reporting. I recently moved the build pipeline from Travis to GitHub actions because Travis stopped working altogether.

Probably something is not configured correctly with GitHub actions. I'll take a look and see if I can fix it.

**Comment by boynux** [comment]
https://github.com/svenstaro/upload-release-action/issues/101#issue-1667903253

**Comment by boynux** [comment]
It's fixed now, let me know if you need further help

**Comment by goganchic** [comment]
@boynux sorry, but you have a typo in artifact name:  squid-expoerter. I think it should be  squid-exporter. Would you please fix it?

**Comment by boynux** [comment]
oh no! it's fixed now :)

**Comment by DanielViard** [comment]
Hello,

Yes it is fixed, thank you !
