### ISSUE TITLE
Add Basic authentication

### ISSUE THREAD

**Issue by techstudio-project** [boynux/squid-exporter#76]
Considering adding Basic certification?

For security reasons,  /metrics endpoint Access should be authenticated before it can be accessed

**Comment by boynux** [comment]
Hi, 

thank for making this request, do you know where I can find more information about squids support for cert authentication? Note that the current implementation of the exporter can use basic auth credentials, but adding cert auths wouldn't be that hard I think.

Also if you want to contribute please send me a PR

**Comment by techstudio-project** [comment]
sorry, I wrote it wrong, I mean add basic authentication on squid-exporter

**Comment by boynux** [comment]
Basic auth is already supported. Please check that out and let me know if you need further help.
