### ISSUE TITLE
Securely Export

### ISSUE THREAD

**Issue by Megabyte516** [boynux/squid-exporter#86]
**Describe the bug**
Just would like to know if there is any plan to incorporate SSL/TLS into this exporter.

**To Reproduce**
None

**Expected behavior**
Allow setting up secure connection to Prometheus server

**OS (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. v0.4]

**Additional context**

**Comment by boynux** [comment]
Hi, I currently don't have any plans to add https/tls support, but feel free to make a pull request and I'll make sure to review it timely.

Thank you!

**Comment by dswarbrick** [comment]
The use of github.com/prometheus/exporter-toolkit would make this trivial to implement, as it provides helper functions for the http server configuration, defined by a config file: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md

**Comment by boynux** [comment]
Thank you for the pointer, I still can't make time for this, although I agree this is a good improvement. However, will gladly review PRs if you or some else has a few spare hours to contribute to this open source project.
